test-defaults: &test-defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8-browsers
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

restore_cache_keys: &restore_cache_keys
  keys:
    - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
    - code-master-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

save_cache: &save_cache
  key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
  paths:
    - node_modules

version: 2
jobs:
  test:
    <<: *test-defaults
    steps:
      - checkout
      - restore_cache: *restore_cache_keys
      # https://github.com/circleci/circleci-images/issues/125
      - run: sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
      - run: sudo tar xf geckodriver-v0.19.1-linux64.tar.gz -C /usr/local/bin
      - run: npm install
      - run: npm run eslint:ci
      - run: npm run test -- --maxWorkers 2
      - run: ./node_modules/.bin/codecov
      - save_cache: *save_cache

  e2e-tests:
    <<: *test-defaults
    steps:
      - checkout
      - restore_cache: *restore_cache_keys
      # https://github.com/circleci/circleci-images/issues/125
      - run: sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
      - run: sudo tar xf geckodriver-v0.19.1-linux64.tar.gz -C /usr/local/bin
      - run: npm install
      - run: ./bin/run.js --local-concurrency 2 --sauce-concurrency 1 'tests/**/*.js'
      - run: ./bin/run.js --local-concurrency 2 --sauce-concurrency 1 'tests-failing/**/*.js' || echo 'FORCED TO PASS'
      - save_cache: *save_cache

workflows:
  version: 2
  commit:
    jobs:
      - test
      - e2e-tests
